const CalendarEntry = require('../models/CalendarEntry');
const Notification = require('../models/Notification');
const User = require('../models/User');

// Helper to get all Sundays for a given year
const getSundaysForYear = (year) => {
  const sundays = [];
  const date = new Date(year, 0, 1);
  while (date.getDay() !== 0) {
    date.setDate(date.getDate() + 1);
  }
  while (date.getFullYear() === year) {
    sundays.push(new Date(date));
    date.setDate(date.getDate() + 7);
  }
  return sundays;
};

// Auto Sunday Generator
exports.autoGenerateSundaysForSchool = async (schoolId, createdById = null) => {
  try {
    const currentYear = new Date().getFullYear();
    const sundays = getSundaysForYear(currentYear);
    
    const entries = sundays.map(sundayDate => {
      const d = new Date(sundayDate);
      d.setHours(0,0,0,0);
      return {
        schoolId,
        date: d,
        dayType: 'holiday',
        title: 'Sunday Holiday',
        isAutoGenerated: true,
        notifyTarget: 'none',
        createdBy: createdById
      };
    });

    await CalendarEntry.insertMany(entries, { ordered: false }).catch(err => {
      // Ignore duplicate key errors if some Sundays exist
    });
    console.log(`Generated Sundays for school: ${schoolId} for year ${currentYear}`);
  } catch (error) {
    console.error('Error auto-generating Sundays:', error);
  }
};

// GET /api/calendar/:schoolId/:month (month is YYYY-MM)
exports.getCalendarByMonth = async (req, res) => {
  try {
    const { schoolId, month } = req.params;
    const [yearStr, monthStr] = month.split('-');
    const year = parseInt(yearStr);
    const monthIdx = parseInt(monthStr) - 1;

    const startOfMonth = new Date(year, monthIdx, 1);
    const endOfMonth = new Date(year, monthIdx + 1, 0, 23, 59, 59, 999);

    const entries = await CalendarEntry.find({
      schoolId,
      date: { $gte: startOfMonth, $lte: endOfMonth }
    }).sort({ date: 1 });

    res.status(200).json({
      status: 'success',
      entries
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// POST /api/calendar (add/override entry)
exports.addCalendarEntry = async (req, res) => {
  try {
    const { date, dayType, title, description, notifyTarget } = req.body;
    const schoolId = req.user.school;
    
    if (!schoolId) {
      return res.status(400).json({ status: 'error', message: 'User must be associated with a school' });
    }

    const parsedDate = new Date(date);
    parsedDate.setHours(0,0,0,0);

    const isSunday = parsedDate.getDay() === 0;

    let entry = await CalendarEntry.findOne({ schoolId, date: parsedDate });
    
    if (entry) {
      entry.dayType = dayType;
      entry.title = title;
      entry.description = description;
      entry.notifyTarget = notifyTarget;
      entry.createdBy = req.user._id;
      if (isSunday) {
        entry.overridesSunday = true;
      }
      await entry.save();
    } else {
      entry = new CalendarEntry({
        schoolId,
        date: parsedDate,
        dayType,
        title,
        description,
        notifyTarget,
        overridesSunday: isSunday,
        createdBy: req.user._id
      });
      await entry.save();
    }

    // Send notifications if needed
    let notificationMessage = '';
    const formattedDate = parsedDate.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });

    if (isSunday && (dayType === 'working' || dayType === 'celebration' || dayType === 'event')) {
      notificationMessage = `⚠️ Sunday ${formattedDate} is a working day! ${title}`;
    } else if (notifyTarget && notifyTarget !== 'none') {
      if (dayType === 'holiday') {
        notificationMessage = `🎉 Holiday ${title} on ${formattedDate}!`;
      } else if (dayType === 'exam') {
        notificationMessage = `📝 Exam on ${formattedDate}: ${title}`;
      } else if (dayType === 'event' || dayType === 'celebration') {
        notificationMessage = `🎊 Event on ${formattedDate}: ${title}`;
      } else {
        notificationMessage = `📅 Calendar Update: ${title} on ${formattedDate}`;
      }
    }

    if (notificationMessage) {
      let recipientRoles = [];
      if (notifyTarget === 'everyone' || isSunday) {
        recipientRoles = ['parent', 'teacher', 'driver'];
      } else if (notifyTarget === 'staff') {
        recipientRoles = ['teacher', 'driver'];
      } else if (notifyTarget === 'parents') {
        recipientRoles = ['parent'];
      }

      if (recipientRoles.length > 0) {
        const usersToNotify = await User.find({ school: schoolId, role: { $in: recipientRoles } });
        const notificationObjects = usersToNotify.map(u => ({
          school: schoolId,
          sender: req.user._id,
          recipient: u._id,
          type: 'general',
          message: notificationMessage
        }));

        if (notificationObjects.length > 0) {
          await Notification.insertMany(notificationObjects);
        }
        
        entry.notificationSent = true;
        await entry.save();
      }
    }

    res.status(200).json({
      status: 'success',
      message: 'Calendar entry saved successfully',
      entry
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// PUT /api/calendar/:id (edit entry)
exports.editCalendarEntry = async (req, res) => {
  try {
    const { id } = req.params;
    const { dayType, title, description, notifyTarget } = req.body;
    
    const entry = await CalendarEntry.findById(id);
    if (!entry) {
      return res.status(404).json({ status: 'error', message: 'Calendar entry not found' });
    }

    entry.dayType = dayType;
    entry.title = title;
    entry.description = description;
    entry.notifyTarget = notifyTarget;
    entry.createdBy = req.user._id;

    await entry.save();

    res.status(200).json({
      status: 'success',
      message: 'Calendar entry updated successfully',
      entry
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// DELETE /api/calendar/:id (delete or revert override)
exports.deleteCalendarEntry = async (req, res) => {
  try {
    const { id } = req.params;
    const entry = await CalendarEntry.findById(id);
    if (!entry) {
      return res.status(404).json({ status: 'error', message: 'Calendar entry not found' });
    }

    const parsedDate = new Date(entry.date);
    const isSunday = parsedDate.getDay() === 0;

    if (isSunday && entry.overridesSunday) {
      entry.dayType = 'holiday';
      entry.title = 'Sunday Holiday';
      entry.description = '';
      entry.isAutoGenerated = true;
      entry.overridesSunday = false;
      entry.notifyTarget = 'none';
      entry.notificationSent = false;
      await entry.save();

      return res.status(200).json({
        status: 'success',
        message: 'Sunday override reverted to Sunday Holiday',
        entry
      });
    } else {
      await CalendarEntry.findByIdAndDelete(id);
      return res.status(200).json({
        status: 'success',
        message: 'Calendar entry deleted successfully'
      });
    }
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// GET /api/calendar/today/:schoolId
exports.getTodayCalendar = async (req, res) => {
  try {
    const { schoolId } = req.params;
    const today = new Date();
    today.setHours(0,0,0,0);

    const entry = await CalendarEntry.findOne({ schoolId, date: today });
    res.status(200).json({
      status: 'success',
      entry: entry || null
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};
