const mongoose = require('mongoose');

const CalendarEntrySchema = new mongoose.Schema({
  schoolId: { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true },
  date: { type: Date, required: true },
  dayType: { 
    type: String, 
    required: true,
    enum: ['working', 'sunday', 'holiday', 'celebration', 'exam', 'half_day', 'event']
  },
  title: { type: String, required: true },
  description: { type: String },
  isAutoGenerated: { type: Boolean, default: false },
  overridesSunday: { type: Boolean, default: false },
  notifyTarget: { 
    type: String, 
    required: true,
    enum: ['everyone', 'staff', 'parents', 'none'],
    default: 'none'
  },
  notificationSent: { type: Boolean, default: false },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

// Ensure unique calendar entry per school per date
CalendarEntrySchema.index({ schoolId: 1, date: 1 }, { unique: true });

module.exports = mongoose.model('CalendarEntry', CalendarEntrySchema);
